### ISSUE TITLE
Any plans for Transform Configuration compatible with Maltego Chlorine 3.6?

### ISSUE THREAD

**Issue by ch40s** [Lookingglass/Maltego#5]
Hi there, do you have any plans to create a Transform Configuration for Maltego Chlorine 3.6?

**Comment by sweinstein89** [comment]
Hi,

Yes, it is on our todo list to create one. Not sure of when that work will
be scheduled though, or how long it will be before they are complete.

Steven

On Fri, Apr 10, 2015 at 5:43 PM, CS <notifications@github.com> wrote:

> Hi there, do you have any plans to create a Transform Configuration for
> Maltego Chlorine 3.6?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Lookingglass/Maltego/issues/5>.
>



-- 
Regards,

Steven Weinstein
Malware Researcher
Lookingglass Cyber Solutions, Inc.

**Comment by ch40s** [comment]
Hi Steven, thanks a lot for your quick reply!
