### ISSUE TITLE
Issue's with using the transform set.

### ISSUE THREAD

**Issue by Darkpaw95** [Lookingglass/Maltego#6]
Hey, I'm having issues using the transform set. I've included a screenshot of this issue below

http://i.imgur.com/XsUwpvk.png

I think it's an issue with api requests but I'm not sure.

**Comment by sweinstein89** [comment]
Hi,

Have you changed the working directory in your settings? Go into manage transforms, then select all of the VT transforms (you can highlight them all at once) and make sure the working directory is changed to wherever your local path containing the transforms is. 

Also to ensure these work properly you must have a private (paid for) API key. 

Please let me know if you're still having issues. 

Steven

**Comment by Darkpaw95** [comment]
Ok, That fixed it. I honestly wish there was a service who offered a fully open and free API for stuff like this. It would be perfect for malware analysis.
