### ISSUE TITLE
returned with exit code 2 error

### ISSUE THREAD

**Issue by MikeLinney** [Lookingglass/Maltego#7]
Hi,

Have followed the instruction https://github.com/Lookingglass/Maltego but get the "returned with exit code 2 error" when i run the transform am using private virus total api and Carbon CE 3.5.3

Please advice

Mike

![maltego-error](https://cloud.githubusercontent.com/assets/11976463/7444395/12ef5c24-f178-11e4-9810-986acefd4cac.PNG)

**Comment by sweinstein89** [comment]
Hi Mike,

What URL are you trying to scan? Also, can you confirm this private API key
is one that is paid for through their subscription service?

Thanks,
Steven

On Sun, May 3, 2015 at 4:38 AM, MikeLinney <notifications@github.com> wrote:

> Hi,
>
> Have followed the instruction https://github.com/Lookingglass/Maltego but
> get the "returned with exit code 2 error" when i run the transform am using
> private virus total api and Carbon CE 3.5.3
>
> Please advice
>
> Mike
>
> [image: maltego-error]
> <https://cloud.githubusercontent.com/assets/11976463/7444395/12ef5c24-f178-11e4-9810-986acefd4cac.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Lookingglass/Maltego/issues/7>.
>



-- 
Regards,

Steven Weinstein
Malware Researcher
Lookingglass Cyber Solutions, Inc.

**Comment by MikeLinney** [comment]
Hi Steven,

Have tried a few urls including www.nullit.net. Virus Total issued a  private key with special academic researcher privileges.

Thanks
Mike

**Comment by sweinstein89** [comment]
Hi Mike,

Trying that example worked for me, with the expected output of " Scan
request successfully queued, run urlToDetectionRatio later".

If you can confirm that you are trying to run that transform with that URL
having a "domain" entity type (domain entity type is required for this
transform), you may want to ask support at VirusTotal if the API key they
have provisioned you allows for URL submissions.

Thanks,
Steven

On Sun, May 3, 2015 at 5:47 AM, MikeLinney <notifications@github.com> wrote:

> Hi Steven,
>
> Have tried a few urls including www.nullit.net. Virus Total issued a
> private key with special academic researcher privileges.
>
> Thanks
> Mike
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Lookingglass/Maltego/issues/7#issuecomment-98460902>.
>



-- 
Regards,

Steven Weinstein
Malware Researcher
Lookingglass Cyber Solutions, Inc.

**Comment by MikeLinney** [comment]
Steven,

Thanks very much for all you help. Done a complete re-install of Maltego and problem solved, not sure what caused the error..but its all working fine now.

Regards

Mike

**Comment by sweinstein89** [comment]
Hi Mike,

Glad to hear that solved the problem, sometimes that's what's needed!

Steven

On Thu, May 7, 2015 at 7:06 PM, MikeLinney <notifications@github.com> wrote:

> Steven,
>
> Thanks very much for all you help. Done a complete re-install of Maltego
> and problem solved, not sure what caused the error..but its all working
> fine now.
>
> Regards
>
> Mike
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Lookingglass/Maltego/issues/7#issuecomment-100043722>.
>



-- 
Regards,

Steven Weinstein
Malware Researcher
Lookingglass Cyber Solutions, Inc.
