### ISSUE TITLE
Transform Configuration compatible with Maltego Chlorine 3.6? 

### ISSUE THREAD

**Issue by gtaibo** [Lookingglass/Maltego#8]
HI,will this project be out anytime this year?

**Comment by sweinstein89** [comment]
Are you getting an error when you try to import the configuration using Chlorine? If so, could you please paste it here? I'm using the transforms with no problem on Chlorine.

**Comment by gtaibo** [comment]
I imported the configuration correctly, and made sure the working directory was fine and also the command line is fine. When doing the transformation below for a hash I get that error.

 hashToDetectionRatio Unknown Error:

Type: <type 'exceptions.ValueError'>

Value:No JSON object could be decoded

**Comment by sweinstein89** [comment]
Is the VirusTotal API key that you're using a free API key or is it a premium/private API key that you paid for?

**Comment by gtaibo** [comment]
Its a public key.

**Comment by sweinstein89** [comment]
Unfortunately that explains the issue. These transforms were built specifically for the VirusTotal private API, which has some endpoints that aren't available with the public API keys.
